---
deployment:
  tasks:
    - export APP_ENV=production
    - ~/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan optimize:clear
    - php artisan config:cache
    - php artisan event:cache
    - php artisan route:cache
    - php artisan view:cache
    - ~/nodevenv/tss.upnet.co.tz/10/bin/npm install
    - ~/nodevenv/tss.upnet.co.tz/10/bin/npm run build
